# Generated by Django 3.2.6 on 2023-04-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
