# Generated by Django 4.2 on 2023-04-15 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0002_delete_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_ultima_actualizacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
