# Generated by Django 3.2.6 on 2023-03-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historiasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=3)),
                ('identificacion', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=1)),
                ('tipoSangre', models.CharField(max_length=3)),
                ('historiaClinica', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='historiasClinicas.historiaclinica')),
            ],
        ),
    ]
