# Generated by Django 3.2.6 on 2023-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
    ]
