# Generated by Django 3.2.6 on 2023-04-15 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historiasClinicas', '0002_delete_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
                ('HistoriaClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiasClinicas.historiaclinica')),
            ],
        ),
    ]
